# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket               = "backend-test-proyects"
    encrypt              = false
    key                  = "terraform.tfstate"
    profile              = "craldo"
    region               = "us-east-1"
    workspace_key_prefix = "infra-basic-alb/resources/ec2/security-group"
  }
}
