# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# variable "workspace_iam_roles" {
#   description = "Variable for credentials management."
#   default = {
#     craldo = "craldo"
#   }
# }
provider "aws" {
  region  = "us-east-1"
  profile = "craldo"
}
